// Narration-synced beats: [scene, line index, fragment of that line ('^' = line start), name, sound].
export default [
  ['hook', 0, 'over a million', 'million', 'pop'],
  ['hook', 1, 'Reviews', 'review', 'pop'],
  ['problem', 1, '^', 'nav', 'pop'],
  ['problem', 1, 'text was small', 'text', 'pop'],
  ['problem', 1, 'reminders stopped', 'reminders', 'pop'],
  ['problem', 1, 'some messages', 'languages', 'pop'],
  ['insight', 1, '^', 'mark', 'impact'],
  ['decision1', 0, 'to the bottom', 'bottom', 'pop'],
  ['decision1', 0, 'message filters', 'filters', 'pop'],
  ['decision1', 1, '^', 'contrast', 'pop'],
  ['decision1', 1, 'asks people', 'asks', 'click'],
  ['decision2', 1, 'booking messages', 'booking', 'pop'],
  ['decision2', 1, 'groups them', 'groups', 'pop'],
  ['decision2', 1, 'a tap', 'tap', 'click'],
  ['decision3', 1, 'pick their', 'pick', 'pop'],
  ['decision3', 1, 'translate any', 'translate', 'shimmer'],
  ['decision3', 1, 'read aloud', 'aloud', 'pop'],
  ['decision3', 1, 'every layout', 'layout', 'pop'],
  ['result', 0, 'preferred', 'preferred', 'pop'],
  ['result', 1, 'Material three', 'material', null],
  ['result', 1, 'thirty percent', 'engagement', 'tick'],
]
