// Narration-synced beats: [scene, line index, fragment of that line ('^' = line start), name, sound].
export default [
  ['problem', 0, 'ninety-nine', 'fee', 'pop'],
  ['problem', 0, 'one in three', 'third', 'pop'],
  ['problem', 1, 'progress', 'progress', null],
  ['problem', 1, 'forty-one', 'vetting', 'pop'],
  ['problem', 1, 'no reason', 'reason', 'pop'],
  ['insight', 1, '^', 'mark', 'impact'],
  ['decision1', 1, 'drop the', 'fee', 'pop'],
  ['decision1', 1, 'Microsoft Entra', 'entra', 'pop'],
  ['decision1', 1, 'explain', 'explain', 'pop'],
  ['decision2', 0, 'three ways', 'three', 'pop'],
  ['decision2', 1, '^', 'document', 'pop'],
  ['decision2', 1, 'pre-fills', 'prefill', 'shimmer'],
  ['decision2', 1, 'people', 'people', 'pop'],
  ['decision3', 1, '^', 'email', 'pop'],
  ['decision3', 1, 'status', 'live', 'pop'],
  ['decision3', 1, 'clear reason', 'reason', 'pop'],
  ['decision3', 1, 'fix issues', 'fix', 'click'],
  ['result', 0, 'pilot', 'pilot', 'pop'],
  ['result', 0, 'every Store', 'rollout', null],
  ['result', 1, 'thirty-five to', 'success', 'tick'],
  ['result', 1, 'fifteen days', 'vetting', 'tick'],
  ['takeaway', 1, '^', 'absorbs', null],
]
