// Narration-synced beats: [scene, line index, fragment of that line ('^' = line start), name, sound].
export default [
  ['hook', 1, 'fifty-two', 'now', null],
  ['hook', 1, 'thirty-one', 'before', null],
  ['problem', 0, 'scores', 'scores', 'pop'],
  ['problem', 1, 'mostly text', 'text', 'pop'],
  ['insight', 1, '^', 'mark', 'impact'],
  ['decision1', 0, 'visual hierarchy', 'hierarchy', 'shimmer'],
  ['decision1', 1, 'at a glance', 'glance', 'pop'],
  ['decision1', 1, 'deeper content', 'deeper', 'pop'],
  ['decision2', 0, 'Cricket', 'cricket', 'pop'],
  ['decision2', 0, 'tennis', 'tennis', 'pop'],
  ['decision2', 0, 'F1', 'f1', 'pop'],
  ['decision2', 0, 'NFL', 'nfl', 'pop'],
  ['decision2', 1, 'shared layer', 'shared', 'shimmer'],
  ['decision2', 1, 'sport layer', 'sport', 'pop'],
  ['decision2', 1, 'data mapping', 'mapping', 'pop'],
  ['decision3', 1, 'Pre-game', 'pre', 'pop'],
  ['decision3', 1, 'live', 'live', 'pop'],
  ['decision3', 1, 'post-game', 'post', 'pop'],
  ['decision3', 1, 'edge cases', 'edge', null],
  ['decision3', 1, 'rain', 'rain', 'tick'],
  ['decision3', 1, 'red flags', 'flags', 'tick'],
  ['decision3', 1, 'super overs', 'overs', 'tick'],
  ['result', 0, 'four sports', 'four', 'pop'],
  ['result', 1, '^', 'redesign', null],
  ['result', 1, 'new shell', 'shell', 'pop'],
  ['takeaway', 0, 'a system property', 'system', null],
]
